-- SYNTAXE


-- DONNE MOI LE PRENOM DES PATIENTS

-- DONNE MOI LE NOM DE FAMILLE DES DOCTEURS

-- DONNE MOI TOUT CE QUE TU SAIS SUR LES PATIENTS

-- DONNE MOI TOUS LES PATIENTS QUI ONT MOINS DE X ANS

-- DONNE MOI TOUS LES CHIRURGIENS

-- DONNE MOI TOUS LES CHIRURGIENS XXXXX

-- + de 1 condition

-- DONNE MOI TOUS LES PATIENTS ORDRéS ALPHABETIQUEMENT

-- COMBIEN DE DOCTEURS?

-- COMBIEN DE CHIRURGIENS?

-- COMBIEN DE DOCTEURS PAR SPECIALITE?


